### PR TITLE
Resolved issues #49 and #52

### LINKED ISSUE #49: The `mapB` Interceptor Error
In `interceptor\internals\main.go`, the .wasm will error out if the data received on line 125, `res, err := client.Do(r)` is nil. 
LINE 136: 
```
	buf := new(bytes.Buffer)
	buf.ReadFrom(res.Body)

	bufByte := buf.Bytes()

	mapB := make(map[string]interface{})
	json.Unmarshal(bufByte, &mapB)

	fmt.Println("mapB: ", mapB)
	toDecode, ok := mapB["data"].(string)
	if !ok {
		res := &utils.Response{
			Status:     500,
			StatusText: "mapB[\"data\"].(string) not 'ok'",
		}
		resByte, _ := res.ToJSON()
		return 500, resByte
	}
```

Error handling is necessary here. Otherwise, this error appears in the browser console: `mapB:  map[],  wasm_exec_v1.js:22,  panic: assignment to entry in nil map`. This panic exits the module requiring a site refresh to re-initialize the wasm module.

### LINKED ISSUE #52: Running Make Command Creates Redundant Folder
@huzaifamk you were correct. If  you clone the repo, it doesn't come with the extra folders. However, running the Make command will create this folder. @DeeStarks, as the author of the Make file, can you fix this issue? I'm afraid to haha.

Folders_L8

### PR DESCRIPTION
**Pull request by DeeStarks**
This PR:
- fixes #49: This issue originates from https://github.com/globe-and-citizen/layer8/blob/6df9a16e979b6400ec62ef4357167f079779cf1b/interceptor/internals/main.go#L57-L59 and is caused by not initializing the `Headers` (a map defined as `map[string]string`) field of the `utils.Response` struct, hence the `assignment to entry in nil map` error. So when the `Client.do` method gets an error from the external calls and returns to the `Client.transfer` method without initializing the `Headers`, it panics as it is in a zero state (`nil`)
- fixes #52 

Other fixes:
- Noticed that the proxy's `Tunnel` handler returns a `401 unauthorized` status for some internal errors, making debugging quite difficult. These were changed to return code `500`
- Also in the `Tunnel` handler, the base64 response data fails to decode in the interceptor (at times). Since `json.Marshal` returns encoded data in `[]byte` type, I thought it might not be necessary to explicitly encode again. This was modified, and the interceptor can simply read the JSON data directly from the buffer without having to explicitly decode again

### CODE REVIEW

**Review by stravid87 — COMMENTED** [review]
For #52 I assume that it will work just fine. 
However, for #49, I can't be sure.
Can you merge into development or stravid87/run_local? branch TIO-Edit is 2 wks out of date now.

**Comment by DeeStarks** [comment]
> For #52 I assume that it will work just fine. However, for #49, I can't be sure. Can you merge into development or stravid87/run_local? branch TIO-Edit is 2 wks out of date now.

Okay. Can you help to test on your end as well?

**Comment by stravid87** [comment]
> > For #52 I assume that it will work just fine. However, for #49, I can't be sure. Can you merge into development or stravid87/run_local? branch TIO-Edit is 2 wks out of date now.
> 
> Okay. Can you help to test on your end as well?

Yup. Let me run it now.

**Comment by stravid87** [comment]
Nice. Even with 2 bonus fixes!!

**Pull request merged**
