### PR TITLE
Merge working development into Production

### PR DESCRIPTION
**Pull request by huzaifamk**

### CODE REVIEW

**Comment by huzaifamk** [comment]
@ternakkode you can merge this after adding necessary variables for the production, like you did for development.

**Comment by huzaifamk** [comment]
@ternakkode once you are done, let me know, I will update the lightsail mocks to use the production server.

**Comment by ternakkode** [comment]
> @ternakkode you can merge this after adding necessary variables for the production, like you did for development.

added, lets deploy this

**Review by ternakkode — APPROVED** [review]
LGTM

**Pull request merged**
