### PR TITLE
[DRAFT] Made changes on sp mock FE and BE to get poem by id

### PR DESCRIPTION
**Pull request by huzaifamk**
## Description
This PR is related to adding the functionalities on the WGP SP Frontend and Backend related to GetPoemByID, and currently this can only be tested with local version of middleware and interceptor as mentioned at the end of this comment. Also once the PRs of middleware: https://github.com/globe-and-citizen/layer8-middleware/pull/19 and interceptor: https://github.com/globe-and-citizen/layer8-interceptor/pull/25 are approved, this can then be tested using npm versions of layer8_middleware and layer8_interceptor respectively.

### SECTION 1: RESOURCE SERVER (http://localhost:5001/)
- [x] http://localhost:5001/ home page loads
- [x] "LoginAsUser" button takes you to the user login page
- [x] Log in using "tester" and "12341234" should succeed
- [x] Updating the display name should work
- [x] Log out and Register a new user and try to log in with that new user
- [x] "LoginAsClient" button takes you to the client login page
- [x] Log in using "layer8" and "12341234" should work
- [x] You will be able to see your UID and Secret in profile
- [x] Log out and Register a new client and log in using that should work

### SECTION 2: WE'VE GOT POEMS (http://localhost:5173/)
- [x] Log in with 'tester' / '1234'
- [x] Log in anonymously with Layer8
- [x] Clicking "Get Next Poem" loads different poem correctly x 3
- [x] Clicking "Logout" takes you to the login screen
- [x] Clicking "Register" takes you to the registration page
- [x] Registering with a username, password, and profile image is successful
- [x] Logging in with the new username / password succeeds
- [x] Logging in with Layer8 opens the pop-up
- [x] Logging in with the newly registered credentials from Section 1 succeeds
- [x] User chooses to share their new "Username" & "Country" from the Layer8 Resource Server
- [x] Clicking "Get Next Poem" loads different poem correctly x 3
- [x] Clicking "Logout" takes you to the login page
- [x] Log in with 'tester' / '1234', and then with the credentials from Section 1 succeeds
- [x] This time, DO NOT share "display name" or "country"
- [x] Clicking "Get Next Poem" loads different poem correctly x 3

### SECTION 3: IMSHARER (http://localhost:5174/)
- [x] Main page loads
- [x] Upload of image works
- [x] Reload leads to instant reload (demonstrating proper caching)
- [x] Clicking the newly loaded image shows it in a lightbox

NOTE: For WGP, this will only work with local version of this middleware: https://github.com/globe-and-citizen/layer8-middleware/tree/hmk/url-decryption-v1 and interceptor: https://github.com/globe-and-citizen/layer8-interceptor/tree/hmk/url-encryption

### CODE REVIEW

**Review by stravid87 — APPROVED** [review]
Looking forward to showing this off to Marc!

**Comment by huzaifamk** [comment]
@stravid87 this PR is ready, and safe to merge, because I just tested the development branch of layer8, with latest development branches of interceptor and middleware, and this is happening there also, image not showing.
image

**Comment by ternakkode** [comment]
Can we remove the commented logs?

**Comment by huzaifamk** [comment]
Ok @ternakkode will do that, but this PR is currently on hold.

**Pull request closed without merging**
